"""
範例 01: Hello RPA - 第一個自動化腳本

功能：
1. 打開記事本
2. 輸入文字
3. 演示基本的自動化操作

學習要點：
- pyautogui 基礎使用
- 時間延遲的重要性
- 錯誤處理

執行：python 01_hello_rpa.py
"""

import time
import pyautogui
import sys

# 設置安全機制
pyautogui.FAILSAFE = True
pyautogui.PAUSE = 0.5

def main():
    print("=" * 60)
    print("Hello RPA - 第一個自動化腳本")
    print("=" * 60)
    print("\n注意：請確保沒有重要工作未保存！")
    print("腳本將在 3 秒後開始執行...")
    print("（將滑鼠移到螢幕左上角可緊急停止）\n")

    time.sleep(3)

    try:
        # 步驟 1: 打開記事本
        print("[1/3] 打開記事本...")
        open_notepad()

        # 步驟 2: 輸入文字
        print("[2/3] 輸入文字...")
        type_hello_message()

        # 步驟 3: 完成
        print("[3/3] 完成！")
        print("\n✅ 腳本執行成功！")
        print("記事本已打開並輸入文字。")
        print("\n按 Ctrl+C 結束程式...")

        # 保持程式運行
        while True:
            time.sleep(1)

    except KeyboardInterrupt:
        print("\n\n程式已停止。")
        sys.exit(0)

    except pyautogui.FailSafeException:
        print("\n\n⚠️  安全停止：滑鼠移到了螢幕左上角")
        sys.exit(0)

    except Exception as e:
        print(f"\n\n❌ 錯誤: {str(e)}")
        print("請檢查系統設置或手動執行測試。")
        sys.exit(1)

def open_notepad():
    """
    打開記事本應用程式
    支援 Windows、macOS 和 Linux
    """
    import platform

    system = platform.system()

    if system == "Windows":
        # Windows: 使用 Win 鍵搜尋
        pyautogui.press('win')
        time.sleep(0.5)
        pyautogui.write('notepad', interval=0.1)
        time.sleep(0.5)
        pyautogui.press('enter')
        time.sleep(1)

    elif system == "Darwin":  # macOS
        # macOS: 使用 Spotlight
        pyautogui.hotkey('command', 'space')
        time.sleep(0.5)
        pyautogui.write('textedit', interval=0.1)
        time.sleep(0.5)
        pyautogui.press('enter')
        time.sleep(1)

    elif system == "Linux":
        # Linux: 嘗試常見的文字編輯器
        pyautogui.hotkey('alt', 'F2')  # 打開運行對話框
        time.sleep(0.5)
        pyautogui.write('gedit', interval=0.1)
        time.sleep(0.5)
        pyautogui.press('enter')
        time.sleep(1)

    else:
        raise Exception(f"不支援的作業系統: {system}")

def type_hello_message():
    """輸入 Hello World 訊息"""

    message = """Hello, RPA World!

This is my first automation script using Python.

Key features demonstrated:
✓ Opening applications
✓ Typing text
✓ Cross-platform support
✓ Error handling

Generated by: RPA + LLM Tutorial
Date: 2024
"""

    # 逐字輸入（設置間隔讓效果更明顯）
    pyautogui.write(message, interval=0.02)

    time.sleep(1)

    # 全選文字
    if platform.system() == "Darwin":
        pyautogui.hotkey('command', 'a')
    else:
        pyautogui.hotkey('ctrl', 'a')

if __name__ == "__main__":
    # 檢查 Python 版本
    import sys
    if sys.version_info < (3, 8):
        print("❌ 需要 Python 3.8 或更高版本")
        sys.exit(1)

    # 檢查依賴
    try:
        import pyautogui
    except ImportError:
        print("❌ 請先安裝 pyautogui: pip install pyautogui")
        sys.exit(1)

    main()
